name: security

on: workflow_dispatch

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scanner:
    name: run osv-scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true
      - name: Upload OSV SARIF
        uses: github/codeql-action/upload-sarif@7434149006143a4d75b82a2f411ef15b03ccc2d7
        with:
          sarif_file: DependenciesAnalysisFull.sarif
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:326e5f41cc972bb423b764a14febbb62bbad29ee1c01820805d077dd868fea48
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Run Semgrep
        run: |
          semgrep scan --config .semgrep --sarif --output SemgrepAnalysis.sarif
        continue-on-error: true
      - name: Upload OSV SARIF
        uses: github/codeql-action/upload-sarif@7434149006143a4d75b82a2f411ef15b03ccc2d7
        with:
          sarif_file: SemgrepAnalysis.sarif
      